matrix:
  include:
  - os: linux
    sudo: false
    dist: trusty
  - os: linux
    sudo: false
    dist: xenial

language: python
python:
- '3.6'

# Only tagged commits
branches:
  except:
  - master

install:
  - pip install -r requirements.txt
  - pyinstaller --version
  - pyinstaller -y helloworld.py

script: ./dist/merlink/merlink
