# .travis.yml used with Travis CI

# Only build if this is a tagged build
matrix:
  include:
    # Ubuntu 16.04
    - os: linux
      sudo: false
      dist: xenial
      language: python
      python: '3.6'

    # OSX 10.13
    - os: osx
      sudo: false
      osx_image: xcode9.4
      language: python
      python: '3.6'

# Only tagged commits
branches:
  only:
    - /^v\d+\.\d+\.\d+$/

# Required for fpm when building rpm
addons:
  apt:
    packages:
      - rpm
      - build-essential

before_install:
  # If target is osx, then brew install python3, pip, venv, and activate venv
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash pkg/macos_pre_install.sh; fi

  # Diagnostic info in case of failure
  - pwd
  - ls
  - echo $PATH
  - echo $TRAVIS_TAG
  - which pip
  - which python
  - pip --version
  - python --version

install:
  - python3 -m pip install -r requirements.txt
  - gem install fpm

script:
  - python3 ./pkg/make_packages.py

### The following was setup with the following ###
# travis setup releases
# travis encrypt <email> --add deploy.username
# travis encrypt <password> --add deploy.password

# Troubleshooting github release + travis ci integration:
# https://docs.travis-ci.com/user/common-build-problems/
#   #I-pushed-a-commit-and-can%E2%80%99t-find-its-corresponding-build

deploy:
  provider: releases
  prerelease: true
  file_glob: true
  file:
    # ${TRAVIS_TAG:1} strips the starting v from the tag
    - build/merlink-${TRAVIS_TAG:1}_x64.deb
    - build/merlink-${TRAVIS_TAG:1}_x64.rpm
    - build/merlink-${TRAVIS_TAG:1}_x64.tar.gz
    - build/merlink-${TRAVIS_TAG:1}_x64.dmg
  on:
    repo: pocc/merlink
    # Only build on a new release tag. $TRAVIS_TAG will be set to that tag.
    tags: true
  # Without this, cleaning will remove what you were planning on deploying
  skip_cleanup: true

  api_key:
    secure: >
      XXuTAZVW7NZVaK7R+3rvTk6rjhwMmzdTf2PvTmeUmyvRzAk8g9bpdVFOJFiRt5XY0L4SqD+O
      08wNUGcA9npeVQF0WibtYx3ZunYluABCQumBDD9DmuwoLeoFM4ZulOnp09nHqp2/InfV7vlZ
      glZ3vbIjwIWdtIHvwQC+LScid69y0yErGQsb+tItacuZONHH30PbfUmX6qNmI0KvD+eIbhKl
      ObTBua4HvEgH0SCAltqO5FoSewl7QoIsMqfHwYGHoMTUhAouimuQNpAdrGTu9tWj+wBocHY7
      Yv1R1z/rxIRzOaGXgn6O3BdlIjnjzc8kx2LWT/k3kn37u4H/fkahlj/ugC1J9Y6AjS9Vu80x
      iV8OqooYnlfRsKOXdM+Ges9lBPFh242oUz0ALojlU1rbc/jLpgZ/mxLJM6Dy08vbhImwITXT
      SG/Q4vgoE1Jp+KYzW5O8wEZGPIUNgrJtM2D5DunHjfoiCY7QEWN9NdHVtDQBaGAu7Qvieg+n
      ECI6H0prPNx/bURkBNEMS+2QFwJuHCaCVKzd/+0Ofv3T9JuHjgIG1j1y8B/Vmst06NNZXPPF
      mJirMNnvAzyZtsA33dt7xMQ3D3Bys1/8LpXQiWFYmDnNlsbqsW5ri+pOFwKD0HbHwpAuw0Vt
      IjuPHJWmp7CAkGoTcgiRdGuoXZ/QgHOPjo4=
