# For appveyor.yml example : https://www.appveyor.com/docs/appveyor-yml/
# For appveyor.yml validation: https://ci.appveyor.com/tools/validate-yaml
# Build environment: https://www.appveyor.com/docs/build-environment/

version: 1.0.{build}
clone_depth: 50                      # clone entire repository history if not defined
# Start builds on tags only (GitHub and BitBucket)
#skip_non_tags: true
# Skipping commits with particular message or from specific user
skip_commits:
  message: /noci/      # Regex for matching commit message
# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
# Check build environment for details. Should have most recent python and ruby versions
image: Visual Studio 2017

# branches to build
branches:
  only:
    - appveyor-ci

# this is how to allow failing jobs in the matrix
matrix:
  allow_failures:
    - platform: x64

# scripts to run before build
install:
  #- cmd: echo This is batch
  #- ps: Write-Host 'This is PowerShell'
  #- ps: C:\Ruby25-x64\bin\ruby.exe  # for any ruby tasks (see build 1.0.5 for more info)
  - C:\Python36\python.exe -m pip install -r requirements.txt
  - ps: $GIT_VERSION=git describe --abrev=0 --tags
  - ps: dir C:\Python36\Lib
  - pyinstaller -y pyinstaller.spec
  # /D specifies additional variables to be used in the script
  - makensis /DPRODUCT_VERSION=GIT_VERSION .\pkg\windows_nsis_installer.nsh

# TESTS (add these at some point)
before_test:
test:
after_test:

notifications:
  - provider: Email
    to:
      - projectmerlink@gmail.com
    subject: 'Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional

deploy:
  release: merlink-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: <your encrypted token> # your encrypted token from GitHub
  # artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: false
  prerelease: true
  on:
    branch: appveyor-ci                 # release from master branch only
    #appveyor_repo_tag: true        # deploy on tag push only